marketplace_fefu/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls'))
]

products/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'products'

urlpatterns = [
    path('category/<slug:category_slug>/', views.category, name='category'),
    path('category/<slug:category_slug>/details/<slug:product_slug>/', views.product, name='product'),
    path('', views.search, name="search"),
    path('buy/<slug:product_slug>', views.buy_product, name='buy_product'),
    path('buy/payment/success/', views.success, name='success'),
    path('buy/payment/failure/', views.failure, name='failure'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

from . import views

urlpatterns = [
    path("register", views.register, name="register"),
    path('login', views.cust_login, name='login'),
    path('logout', views.cust_logout, name='logout'),
    path('profile/<username>', views.profile, name='profile'),
    path('profle/<username>/create_product', views.create_product, name='create_product'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/models.py
from io import BytesIO
from os import name
from PIL import Image
from django.core.files import File
from pytils.translit import slugify
from django.core.validators import MinValueValidator

from django.db import models
from users.models import User
from django.utils import timezone
from uuid import uuid4
from django.urls import reverse

class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=55)
    ordering = models.IntegerField(default=0)


    class Meta:
        ordering = ['ordering']
        verbose_name_plural = "Categories"


    def __str__(self):
        return self.title
    
    def unique_slug(self):
        unique_slug = slugify(self.title)
        return '{}'.format(unique_slug)
    
    def save(self, *args, **kwargs):
        self.slug = self.unique_slug()
        return super(Category, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("category", kwargs={'category_slug': self.slug})
    
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, null=True)
    vendor = models.ForeignKey(User, related_name="products", on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50, default="product")

    slug = models.SlugField(null=True, max_length=55)
    description = models.TextField(blank=True, null=True)
    
    price = models.DecimalField(
        default=0,
        max_digits=6,
        decimal_places=2,
        validators = [MinValueValidator(0)]
        )
    
    add_date = models.DateTimeField(default=timezone.now)
    change_date = models.DateTimeField(default=timezone.now)
    
    image = models.ImageField(upload_to='products', blank=True, null=True, unique=True)

    class Meta:
        ordering = ['-add_date']


    def save(self, *args, **kwargs):
        if not self.id:
            self.add_date = timezone.now()
        self.change_date = timezone.now()
        self.slug = self.unique_slug()
        return super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    def unique_slug(self):
        unique_slug = slugify(self.title)
        return '{}_{}'.format(unique_slug, self.pk)
    
    def get_absolute_url(self):
        return reverse("product_detail", kwargs={'product_slug': self.slug})
    

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from users.models import User
from .models import Product, Category
from django.db.models import Q

def category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    context = {'category': category}
    return render(request, 'products/category.html', context)


def product(request, category_slug, product_slug):
    product = get_object_or_404(Product, slug=product_slug)
    context = {'product': product}
    return render(request, 'products/product_detail.html', context)


def search(request):
    query = request.GET.get('query', '')
    products = Product.objects.all()
    categories = Category.objects.all()
    category_slug = request.GET.get('category', 0)
    if query:
        products = products.filter(Q(title__icontains=query) | Q(description__icontains=query))
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category = category)

    context = {'products': products, 'query': query, 'categories': categories}

    return render(request, 'products/search.html', context)


@login_required
def buy_product(request, product_slug):
    product = get_object_or_404(Product, slug=product_slug)
    user = request.user
    vendor = product.vendor
    if user.balance >= product.price and vendor.username != user.username:
        user.balance -= product.price
        user.save()
        vendor.balance += product.price
        vendor.save()
        product.delete()
        return redirect('payment/success/')
    
    return redirect('payment/failure/')


def success(request):
    return render(request, 'products/success.html')


def failure(request):
    return render(request, 'products/failure.html')

templates/products/category.html
{% extends "core/base.html" %}
{% block content %}
    <div class="main-content">
        <!-- TODO: logo here? -->
        
        <div class="offers">
            <div class="categories">
                {% include "core/categories.html" %}
            </div>
            <div class="search-posts">
                {% include "core/searchbar.html" %}
                <div class="posts">
                    <ul class="posts-list">
                        {% for product in category.products.all %} <!-- TODO: rename variable for backend -->
                            <div class="post-inner">
                                <div class="post-photo">
                                </div>
                                <div>
                                    <div class="post-header">
                                        <a href="{% url 'products:product' product.category.slug product.slug %}"><h3>{{ product.title }}</h3></a>
                                    </div>
                                    <div class="post-short-desc">
                                        <div class="post-price">
                                            {{ product.price }} ₽
                                        </div>
                                        <div class="post-location">
                                        </div>
                                        <div class="post-data">
                                            {{ product.add_date }}
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/products/failure.html
{% extends "core/base.html" %}
{% block content %}
  <div class="main-block">
      <div class="payment-block">
          <div class="payment-anno">
              Недостаточно средств
          </div>
          <a href={% url 'users:profile' request.user.username %} class="comeback-link">
              Вернуться назад
          </a>
      </div>
  </div>
{% endblock %}

templates/products/product_detail.html
{% extends "core/base.html" %}
{% block content %}
<p>{{product.title}}</p>
<p>{{product.add_date}}</p>
<p>{{product.price}}</p>
<p>{{product.description}}</p>
{% if request.user.is_authenticated and request.user != product.vendor %}
<form action="{% url 'products:buy_product' product.slug %} " method="post">
    {% csrf_token %}
    <input type="submit" value="Купить">
</form>
{% endif %}
                            

{% endblock %}

templates/products/search.html
{% extends "core/base.html" %}
{% block content %}
    <div class="main-content">
        <!-- TODO: logo here? -->
        
        <div class="offers">
            <div class="categories">
                {% include "core/categories.html" %}
            </div>
            <div class="search-posts">
                {% include "core/searchbar.html" %}
                <div class="posts">
                    <ul class="posts-list">
                        {% for product in products %} <!-- TODO: rename variable for backend -->
                            <div class="post-inner">
                                <div class="post-photo">
                                    <a href="">{{ posts|default:"error loading post image" }}<img> <!-- TODO: image parse --> </a>
                                </div>
                                <div>
                                    <div class="post-header">
                                        <a href="{% url 'products:product' product.category.slug product.slug %}"><h3>{{ product.title }}</h3></a>
                                    </div>
                                    <div class="post-short-desc">
                                        <div class="post-price">
                                            {{ product.price |default:"error loading post price" }} ₽
                                        </div>
                                        <div class="post-location">
                                        </div>
                                        <div class="post-data">
                                            {{ product.add_date |default:"error loading post data" }}
                                        </div>
                                    </div>
                                </div>
                            </div> 
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/products/success.html
{% extends "core/base.html" %}
{% block content %}
  <div class="main-block">
      <div class="payment-block">
          <div class="payment-anno">
              Покупка успешна
          </div>
          <a href={% url 'products:search' %} class="comeback-link">
              Вернуться назад
          </a>
      </div>
  </div>
{% endblock %}