marketplace_fefu/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls'))
]

products/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'products'

urlpatterns = [
    path('category/<slug:category_slug>/', views.category, name='category'),
    path('category/<slug:category_slug>/details/<slug:product_slug>/', views.product, name='product'),
    path('', views.search, name="search"),
    path('buy/<slug:product_slug>', views.buy_product, name='buy_product'),
    path('buy/payment/success/', views.success, name='success'),
    path('buy/payment/failure/', views.failure, name='failure'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

from . import views

urlpatterns = [
    path("register", views.register, name="register"),
    path('login', views.cust_login, name='login'),
    path('logout', views.cust_logout, name='logout'),
    path('profile/<username>', views.profile, name='profile'),
    path('profle/<username>/create_product', views.create_product, name='create_product'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Маркетплейс ДВФУ</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="top-navbar">
            <nav class="navbar">
                <ul class="ul-navbar">
                    <li>
                        <a href=""><img></a>
                    </li> <!-- TODO: add a logo image here -->
                    <li>
                        <a href="{% url 'products:search' %}">Главная</a>
                    </li>
                </ul>
            </nav>
            <ul class="ul-navbar">
                <li>
                    <a href="">Избранное</a> &nbsp; <!-- TODO: add links -->
                </li>
                <li>
                    <a href=""><img> {{ first_name|default:"" }} {{ second_name|default:"" }} </a> <!-- TODO: add avatar parsed from vk-->
                </li>
                {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url "users:profile" request.user.username %}">Профиль</a>
                {% else %}
                    <a href="{% url "users:login" %}">Log-in &nbsp;</a>
          
                    <a href="{% url "users:register" %}">Reg</a>
                </li>
                {% endif %}
            </ul>
        </div>
        {% block content %}

        {% endblock %}
        <footer class="footer-main">
            <ul class="ul-footer">
                <li >
                    Сайт-маркетплейс для студентов &nbsp;
                </li>
                <li>
                    <a href="">Контакты</a>
                </li>
            </ul>
        </footer>
    </body>
</html>

templates/core/categories.html
{% block content %}
    <ul class="categories-list">
        {% for category in categories %}
        <li {%if category.slug == category_slug%} {%endif%}> <!-- add class=bg gray between if endif-->
            <a href="{% url 'products:search'%}?query={{query}}&category={{category.slug}}">
                {{category.title}}
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/core/searchbar.html
{% block content %}
    <div class="search-bar">
        <form action="{%url 'products:search' %}" method="get">
            <input type="text" name="query" class="main-search" placeholder="Провести поиск по сайту..." autocomplete="off" spellcheck="false" value={{query}} >
            <button class="search-button"><img>Поиск</button> <!-- TODO: add lupa image -->
        </form>
    </div>
{% endblock %}