marketplace_fefu/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('products.urls'))
]

products/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'products'

urlpatterns = [
    path('category/<slug:category_slug>/', views.category, name='category'),
    path('category/<slug:category_slug>/details/<slug:product_slug>/', views.product, name='product'),
    path('', views.search, name="search"),
    path('buy/<slug:product_slug>', views.buy_product, name='buy_product'),
    path('buy/payment/success/', views.success, name='success'),
    path('buy/payment/failure/', views.failure, name='failure'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

from . import views

urlpatterns = [
    path("register", views.register, name="register"),
    path('login', views.cust_login, name='login'),
    path('logout', views.cust_logout, name='logout'),
    path('profile/<username>', views.profile, name='profile'),
    path('profle/<username>/create_product', views.create_product, name='create_product'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


from django.urls import reverse

class User(AbstractUser):

    email = models.EmailField(max_length=254)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    vk = models.CharField(max_length=255, blank=False, null=False)
    image = models.ImageField(upload_to='users', blank=True, null=True)
    balance = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.username

    

users/forms.py
from django.forms import ModelForm, models, Form
from products.models import Product
from django import forms
from .models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['category', 'image', 'title', 'description', 'price']
    
    def save(self, commit=True):
        product = super(ProductForm, self).save(commit=False)
        if self.cleaned_data['image']:
            product.image = self.cleaned_data['image']
            product.save()
        return product


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username','vk', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user
    
class UserLoginForm( AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username or Email'}),
        label="Username or Email*")

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'vk']

users/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404

from django.contrib.auth import login, get_user_model, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from products.models import Product
from .models import User

from .decorators import user_not_authenticated
from .forms import UserRegistrationForm, UserLoginForm, UserUpdateForm, ProductForm


@user_not_authenticated
def register(request):
    if request.user.is_authenticated:
        return redirect("profile/" + request.user.username)
    
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("profile/"+request.user.username)
    
    else:
        form = UserRegistrationForm()

    return render(
        request=request,
        template_name='users/registration.html',
        context={'form': form})


@login_required
def cust_logout(request):
    logout(request)
    return redirect('/')


@user_not_authenticated
def cust_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                username = user.get_username()
                return redirect("profile/" + request.user.username)
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)
    form = UserLoginForm()

    return render(
        request=request,
        template_name='users/login.html',
        context={'form': form}
    )


def profile(request, username):
    user = User.objects.get(username=username)
    if user.username != request.user.username:
        return redirect('/')
    if user:
        products = user.products.all()
        
        return render(
            request=request,
            template_name="users/profile.html",
            context={'products': products}
            )

    return redirect("/")

def create_product(request, username):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        
        if form.is_valid():
            product = form.save()
            product.vendor = request.user
            product.save()
            previous_page = request.GET.get('next') if request.GET.get('next') is not None else ''
            return redirect(previous_page) if previous_page != '' else redirect('/')
    
    form = ProductForm()
    return render(request, 'users/create_product.html', {'form': form})

templates/users/create_product.html
{% extends "core/base.html" %}
{% block content %}
	<div class="create-product">
	    <div class="cr-pr">
		<div class="create-product-h">
		    Выберите категорию
		</div>
		<div id="choose-category">
		    <select class="choose-category-select">
			<option selected disabled>
			    Категории
			</option>
			<option value="Еда">
			    Еда
			</option>
			<option value="Электроприборы">
			    Электроприборы
			</option>
			<option value="Бытовые товары">
			    Бытовые товары
			</option>
			<option value="Услуги">
			    Услуги
			</option>
		    </select>
		</div>
		<div class="create-product-h">
		    Информация о товаре
		</div>
		<div class="ad-main-content-block">
		    <div class="info-h">
			Название товара
		    </div>
		    <input type="text" id="info-bar-product-name">
		    <div class="info-h">
			Цена
		    </div>
		    <div id="info-ad-price">
			<input type="text" id="info-bar-product-price">
			<div id="ruble">
			    ₽
			</div>
		    </div>
		    <div class="info-h">
			Текст объявления
		    </div>
		    <textarea type="text" id="info-bar-product-description" wrap="soft"></textarea>
		</div>
		<div class="create-product-h">
		    Условия продажи
		</div>
		<div class="ad-main-content-block">
		    <div class="info-h">
			Доставка
		    </div>
		    <input type="text" class="info-bar-product-sales-conditions">
		    <div class="info-h">
			Оплата
		    </div>
		    <input type="text" class="info-bar-product-sales-conditions">
		    <div class="info-h">
			Контакты
		    </div>
		    <input type="text" class="info-bar-product-sales-conditions">
		</div>
		<form action="{% url 'products:search' %}" class="cr-pr-button">
		    <button class="universal-button">
			Создать
		    </button>
		</form>
	    </div>
	</div>
{% endblock %}

templates/users/login.html
{% extends "core/base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <h2>Log in</h2>
    {% for field in form %}
	<p>
	 	{{ field.label_tag }} {{ field }}
	</p>
	{% endfor %}
	<input type="submit" value="Log in" />
</form>

{% endblock %}

templates/users/logout.html
{% extends "core/base.html" %}
{% block content %}

<p>Success</p>
{% endblock %}

templates/users/profile.html
{% extends "core/base.html" %}
{% block content %}
    <div class="profile">
        <div class="nav-profile">
            <div>
                <div id="avatar-photo">
                    {{ users.image }}
                </div>
                <div id="name"> <!-- username-->
                    Логин: &nbsp; {{ request.user.username }}
                </div>
                <!-- first_name-->
                <div id="city-id">
                    Имя: &nbsp; {{request.user.first_name}}
                </div>
                <div id="city-id">
                    Фамилия: &nbsp; {{request.user.last_name}}
                </div>
                <div id="city-id">
                    Баланс: &nbsp; {{request.user.balance}}руб.
                </div>
            </div>
            <ul id="advertisement-info">
                <li>
                    <ul class="category">
                        <li class="profile-settings">
                            <a href="{% url "users:create_product" request.user.username %}?next={{request.path}}" class="profile-links">Добавить товар</a>
                        </li>
                        <li class="profile-settings">
                            Архив
                        </li>
                        <li class="profile-settings">
                            <a href="{% url 'products:search' %}" class="profile-links">
                                Все объявления
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <ul class="category">
                        <li class="profile-settings">
                            <a href="{% url "users:profile" request.user.username %} class="profile-links"">Мой профиль</a>
                        </li>
                        <li class="profile-settings">
                            Настройки профиля
                        </li>
                        <li class="profile-settings">
                            <a href="{% url 'users:logout'%}" class="profile-links">Выйти из профиля</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="advertisement">
            <div id="advertisement-header">
                <b>Объявления</b>
            </div>
            {% if !products %}
                <div class="ad-button">
                    <span id="is-advertisement">
                        Объявлений нет
                    </span>
                    <form action="{% url 'users:create_product' request.user.username %}">
                        <button class="universal-button">
                            Создать
                        </button>
                    </form>
                </div>
            {% else %}
                {% for product in products %}
                    <form action="{% url 'products:product' product.category.slug product.slug %}" class="ad-form">
                        <button class="ad">
                            <div id="ad-date">  
                                {{product.add_date}}
                            </div>
                            <div id="ad-name">
                                {{product.title}}
                            </div>
                            <div class="ad-info-with-photo">
                                <div class="ad-info">
                                    <div id="price">
                                        {{product.price}}  руб.
                                    </div>
                                    <div id="description">
                                        {{product.description}}
                                    </div>
                                </div>
                                <div class="ad-photo-dir">
                                    <div id="ad-photo">
                                        {{product.image}}
                                    </div>
                                </div>
                            </div>
                        </button>
                    </form>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/registration.html
{% extends "core/base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <h2>Sign Up</h2>
    {% for field in form %}
	<p>
		{% if field.errors %}
		<ul class="errorlist">
			{% for error in field.errors %}
			<li>{{ error }}</li>
			{% endfor %}
		</ul>
		{% endif %}
	 	{{ field.label_tag }} {{ field }}
	</p>
	{% endfor %}
	<input type="submit" value="Register" />
</form>

{% endblock %}